server:
  port: 8081

spring:
  security:
    user:
      name: hamdyYml
      password: hamdyYml123
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/orclpdb
    username: ff
    password: ff
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  messages:
    basename: i18n/message
  data:
   redis:
     host: localhost
     port: 6379
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
token:
  secret: mysupersecretkeymysupersecretkey1234
  time: 24H


app:
  upload:
    dir: F:\Eraasoft Java Course\Projects\friend-finder-eraasoft-main\friend-finder-eraasoft-main/uploads/